CREATE NONCLUSTERED INDEX [NCI_GLPostingTransactions_control_loaded] ON [dbo].[DBA_GLPostingTransactions_control]
(
	 [RowNbr] ASC
)
INCLUDE([loaded],[Skey],[PostTime]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

